theme: jekyll-agency
url: "https://professionalwithstandards.github.io"
baseurl: "/My-Bio"

# Site settings
title: My Bio
email: Mysticism.occult@gmail.com
description: "A brief about Hraday Vaidya"


# Team names, titles and social links
people:
- name:   
  pic: 1.jpg
  position:   
  



# Build settings
markdown: kramdown
permalink: pretty
